### ISSUE TITLE
Race condition in testRebotBackend

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#175] opened 2020-08-19 14:55 UTC
failed in tsan build, but not in others -> race condition
```
test 49
      Start 49: testRebotBackend

49: Test command: /scratch/build-ChimeraTK-DeviceAccess/scripts/testRebotBackend.sh
49: Test timeout computed to be: 9.99988e+06
49: Rebot dummy server started
49: Running 2 test cases...
49: 
49: *** No errors detected
49: Running 2 test cases...
49: 
49: *** No errors detected
49: Running 1 test case...
49: 
49: *** No errors detected
49: Rebot dummy server stopped
49: Running 2 test cases...
49: /scratch/source/tests/unitTestsNotUnderCtest/testRebotBackend.cpp(119): error in "RebotTestClass::testConnection": exception thrown by rebotBackend.open()
49: /scratch/source/tests/unitTestsNotUnderCtest/testRebotBackend.cpp(121): error in "RebotTestClass::testConnection": check rebotBackend.isOpen() == true failed [false != true]
49: Rebot dummy server started
49: 
49: *** 2 failures detected in test suite "Rebot backend test suite"
49: Testing backed using the IP addess with protocol version 1 failed!
49: Running 2 test cases...
49: 
49: *** No errors detected
49: Running 1 test case...
49: 
49: *** No errors detected
49: Rebot dummy server stopped
49/52 Test #49: testRebotBackend ..............................***Failed   15.01 sec
```

**Comment by mhier** [comment] 2020-09-11 14:25
Duplicate of #174

**Closed by mhier** 2020-09-11 14:25 UTC
