### ISSUE TITLE
Lock acquiring  in SharedMemoryManager blocks forever after previous stopped application

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/DeviceAccess#112] opened 2020-02-10 14:56 UTC
In my application I use the shared memory backend. Currently I try to debug this application, which throws an exception. 

When I start the application again it is not starting any more and stops at the lock acquiring of the SharedMemoryManager:https://github.com/ChimeraTK/DeviceAccess/blob/497c58d0ffb5c66c323d4b07e25bbd0fd7db5ed1/device_backends/SharedDummy/src/SharedMemoryManager.cc#L26

So far I have to reboot the machine in order to use the shared memory access backend again.
I tried to use `ipcs -m` to find a shared memory that is still blocked but none was referred to my application or the process of my already dead application.

It would already help to know how to recover the backend without rebooting the machine, which feels stupid.

**Comment by mhier** [comment] 2020-02-10 15:19
This is a duplicate of #96.

There is a workaround when running into this problem, just run the following command:
```
rm -f /dev/shm/*ChimeraTK*
```
This will remove the shared memory instances of *all* SharedMemoryDummies on your machine, but it avoids a rebood.

**Closed by mhier** 2020-02-10 15:19 UTC
